/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import practico5grupo3.Directorio;

/**
 *
 * @author Fede-
 */
public class BuscarTelefonoPorApellido extends javax.swing.JInternalFrame {
private DefaultTableModel modelo=new DefaultTableModel();
DefaultListModel<String> modeloList = new DefaultListModel<>();
private List<String> apellidos = new ArrayList<>();
    /**
     * Creates new form Frm_BuscarTelefonoPorApellido
     */
    public BuscarTelefonoPorApellido() {
        initComponents();
        buscarApellido();
        cabecera();
        buscarApellido();
        
        jtfApellido.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                filtrarLista();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                filtrarLista();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                filtrarLista();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblBcarTelPrApellido = new javax.swing.JLabel();
        jlbApellido = new javax.swing.JLabel();
        jtfApellido = new javax.swing.JTextField();
        jbsalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListApellidos = new javax.swing.JList<>();

        jblBcarTelPrApellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblBcarTelPrApellido.setText("Buscar Teléfono por Apellido");

        jlbApellido.setText("Apellido:");

        jbsalir.setText("Salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        jtbla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Dirección", "Ciudad", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbla);

        jListApellidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListApellidosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListApellidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbsalir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(173, 173, 173)
                            .addComponent(jblBcarTelPrApellido))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jlbApellido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jtfApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jblBcarTelPrApellido)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jbsalir)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbsalirActionPerformed

    private void jListApellidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListApellidosValueChanged
        // TODO add your handling code here:
        if(!evt.getValueIsAdjusting() && jListApellidos.getSelectedValue() != null){
        String apellido = jListApellidos.getSelectedValue();
        jtfApellido.setText(apellido);
        
        
        modelo.setRowCount(0);
        
        List<Object[]> lista = new Directorio().buscarContactosPorApellido(apellido);
        
            for (Object[] fila : lista) {
                modelo.addRow(fila);
            }
        
        }
                 
    }//GEN-LAST:event_jListApellidosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListApellidos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jblBcarTelPrApellido;
    private javax.swing.JButton jbsalir;
    private javax.swing.JLabel jlbApellido;
    private javax.swing.JTable jtbla;
    private javax.swing.JTextField jtfApellido;
    // End of variables declaration//GEN-END:variables
    private void cabecera (){
        modelo.addColumn("DNI");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        modelo.addColumn("Dirección");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Teléfono");
        jtbla.setModel(modelo);
    }
private void buscarApellido(){
        modeloList.clear();
        apellidos.clear();
        
        for (String ape : new Directorio().obtenerTodosLosApellidos()) {
            modeloList.addElement(ape);
            apellidos.add(ape);
        }
        jListApellidos.setModel(modeloList);
    }
    
    private void filtrarLista(){
        String texto = jtfApellido.getText().trim();
        modeloList.clear();
        
        for (String ape : apellidos) {
            if(ape.startsWith(texto)){
                modeloList.addElement(ape);
            }
        }
    }
}

