
package vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import practico5grupo3.Contacto;
import practico5grupo3.Directorio;

/**
 *
 * @author Fede-
 */
public class BuscarClienteCiudad extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmBuscarClienteCiudad
     */
    DefaultTableModel modeloTabla = new DefaultTableModel();
    
    public BuscarClienteCiudad() {
        initComponents();
        cargarCiudades();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbBuscarClientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTContacto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLCiudades = new javax.swing.JList<>();
        jblCiudades = new javax.swing.JLabel();
        jcbCiudades = new javax.swing.JComboBox<>();
        jBSalir = new javax.swing.JButton();

        jlbBuscarClientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbBuscarClientes.setForeground(new java.awt.Color(0, 0, 0));
        jlbBuscarClientes.setText("Buscar Cliente De Directorio Por Ciudad");

        jTContacto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Direccion", "Ciudad", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(jTContacto);

        jScrollPane2.setViewportView(jLCiudades);

        jblCiudades.setForeground(new java.awt.Color(0, 0, 0));
        jblCiudades.setText("Ciudades:");

        jcbCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCiudadesActionPerformed(evt);
            }
        });

        jBSalir.setForeground(new java.awt.Color(0, 0, 0));
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBSalir)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jblCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jlbBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jblCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jBSalir)
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCiudadesActionPerformed
        // TODO add your handling code here:
        String ciudadSeleccionada= (String) jcbCiudades.getSelectedItem();
        if(ciudadSeleccionada !=null){
            cargarContactosPorCiudad(ciudadSeleccionada);
        }
    }//GEN-LAST:event_jcbCiudadesActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void cargarCiudades(){
        jcbCiudades.removeAllItems();
        for(String ciudad: Directorio.todasLasCiudades()){
            jcbCiudades.addItem(ciudad);
        }
    }
    
    private void inicializarTabla(){
        modeloTabla.addColumn("DNI");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Direccion");
        modeloTabla.addColumn("Ciudad");
        modeloTabla.addColumn("Telefono");
        jTContacto.setModel(modeloTabla);
    }
    
    private void cargarContactosPorCiudad(String ciudad){
        modeloTabla.setRowCount(0); 
        
        ArrayList<Contacto> contactos= Directorio.contactosPorCiudad(ciudad);
        
        
        for(Contacto c: contactos){
            Long telefono= Directorio.BuscarTlefonoPorContacto(c);
            modeloTabla.addRow(new Object[]{
                c.getDni(),
                c.getApellido(),
                c.getNombre(),
                c.getDireccion(),
                c.getCiudad(),
                telefono
            });
        }
        
        jTContacto.setModel(modeloTabla);
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JList<String> jLCiudades;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTContacto;
    private javax.swing.JLabel jblCiudades;
    private javax.swing.JComboBox<String> jcbCiudades;
    private javax.swing.JLabel jlbBuscarClientes;
    // End of variables declaration//GEN-END:variables
    
}
