/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author alybe
 */
public class MenuPrincipal extends javax.swing.JFrame {

//    public static Object getDirectorio() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiAgregarCliente = new javax.swing.JMenuItem();
        jmiBuscarCliente = new javax.swing.JMenuItem();
        jmiBorrarCliente = new javax.swing.JMenuItem();
        jmDirectorio = new javax.swing.JMenu();
        jmBuscarClientesPorCiudad = new javax.swing.JMenuItem();
        jmBuscarTelefonoPorApellido = new javax.swing.JMenuItem();
        jmCiudades = new javax.swing.JMenu();
        jmiAgregarCiudad = new javax.swing.JMenuItem();
        JmSalir = new javax.swing.JMenu();
        JmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        jmClientes.setText("Clientes");

        jmiAgregarCliente.setText("AgregarCliente");
        jmiAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(jmiAgregarCliente);

        jmiBuscarCliente.setText("BuscarCliente");
        jmiBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(jmiBuscarCliente);

        jmiBorrarCliente.setText("BorrarCliente");
        jmiBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(jmiBorrarCliente);

        jMenuBar1.add(jmClientes);

        jmDirectorio.setText("Directorio");

        jmBuscarClientesPorCiudad.setText("BuscarClientesPorCiudad");
        jmBuscarClientesPorCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarClientesPorCiudadActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmBuscarClientesPorCiudad);

        jmBuscarTelefonoPorApellido.setText("BuscarTelefonoPorApellido");
        jmBuscarTelefonoPorApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarTelefonoPorApellidoActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmBuscarTelefonoPorApellido);

        jMenuBar1.add(jmDirectorio);

        jmCiudades.setText("Ciudades");

        jmiAgregarCiudad.setText("AgregarCiudad");
        jmiAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarCiudadActionPerformed(evt);
            }
        });
        jmCiudades.add(jmiAgregarCiudad);

        jMenuBar1.add(jmCiudades);

        JmSalir.setText("Salir");

        JmiSalir.setText("Salir");
        JmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiSalirActionPerformed(evt);
            }
        });
        JmSalir.add(JmiSalir);

        jMenuBar1.add(JmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmBuscarTelefonoPorApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarTelefonoPorApellidoActionPerformed
        // TODO add your handling code here:
        Frm_BuscarTelefonoPorApellido btpa=new Frm_BuscarTelefonoPorApellido();
        btpa.setVisible(true);
        escritorio.add(btpa);
        escritorio.moveToFront(btpa);
    }//GEN-LAST:event_jmBuscarTelefonoPorApellidoActionPerformed

    private void JmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JmiSalirActionPerformed

    private void jmiAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarClienteActionPerformed
        // TODO add your handling code here:
        FrmAgregarCliente ac=new FrmAgregarCliente();
        ac.setVisible(true);
        escritorio.add(ac);
        escritorio.moveToFront(ac);
    }//GEN-LAST:event_jmiAgregarClienteActionPerformed

    private void jmiBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarClienteActionPerformed
        // TODO add your handling code here:
        FrmBuscar buscar=new FrmBuscar();
        buscar.setVisible(true);
        escritorio.add(buscar);
        escritorio.moveToFront(buscar);
    }//GEN-LAST:event_jmiBuscarClienteActionPerformed

    private void jmiBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarClienteActionPerformed
        // TODO add your handling code here:
        FrmBorrar borrar=new FrmBorrar();
        borrar.setVisible(true);
        escritorio.add(borrar);
        escritorio.moveToFront(borrar);
    }//GEN-LAST:event_jmiBorrarClienteActionPerformed

    private void jmBuscarClientesPorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarClientesPorCiudadActionPerformed
        // TODO add your handling code here:
        FrmBuscarClienteCiudad bc=new FrmBuscarClienteCiudad();
        bc.setVisible(true);
        escritorio.add(bc);
        escritorio.moveToFront(bc);
    }//GEN-LAST:event_jmBuscarClientesPorCiudadActionPerformed

    private void jmiAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarCiudadActionPerformed
        // TODO add your handling code here:
        FrmAgregarCiudad aCiudad=new FrmAgregarCiudad();
        aCiudad.setVisible(true);
        escritorio.add(aCiudad);
        escritorio.moveToFront(aCiudad);
    }//GEN-LAST:event_jmiAgregarCiudadActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JmSalir;
    private javax.swing.JMenuItem JmiSalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmBuscarClientesPorCiudad;
    private javax.swing.JMenuItem jmBuscarTelefonoPorApellido;
    private javax.swing.JMenu jmCiudades;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmDirectorio;
    private javax.swing.JMenuItem jmiAgregarCiudad;
    private javax.swing.JMenuItem jmiAgregarCliente;
    private javax.swing.JMenuItem jmiBorrarCliente;
    private javax.swing.JMenuItem jmiBuscarCliente;
    // End of variables declaration//GEN-END:variables
}
